### ISSUE TITLE
Please release these vectors in text form

### ISSUE THREAD

**Issue by DinoChiesa** [Anti-weakpasswords/PBKDF2-Test-Vectors#1]
Thanks for the effort of producing the test vectors.
They're not web-usable when released in .ods format. 

Why not just a text form? As if found in an IETF RFC . 

Simple. Easy. Everyone can read them. No special app or tool required.

**Comment by Anti-weakpasswords** [comment]
This .ods - Libreoffice Calc - file is explicitly a test vector generator.
You can see the actual test vectors in actual (specific) text form in my other various PBKDF2 implementation repositories in the form of pbkdf2_test.bat and pbkdf2_test.sh and similar files.
